[project]
name = "blueprinter-backend"
version = "0.1.0"
description = "FastAPI backend for Blueprinter"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.111",
  "uvicorn[standard]>=0.29",
  "pydantic>=2.7",
  "pydantic-settings>=2.3",
  "httpx>=0.27",
]

[tool.uvicorn]
factory = false

